title: Abhinav Saxena
description: An avid security and software researcher, student.

url: http://xandfury.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: xandfury
   # twitter: brianmaierjr
   # facebook: brianmaierjr
   email: xandfury@gmail.com

google_analytics: "UA-89106408-1"
